### ISSUE TITLE
microhttpd.h: No such file or directory

### ISSUE THREAD

**Issue by MVoz** [cyberpro4/cremi#2]
remi_server.cpp(2): fatal error C1083:

"E:\tools\temp\cremi\cremi.sln" (целевой объект по умолчанию) (1) ->
"E:\tools\temp\cremi\cremi.vcxproj" (целевой объект по умолчанию) (2) ->
(Целевой объект ClCompile) ->
  remi_server.cpp(2): fatal error C1083: Не удается открыть файл включение: microhttpd.h: No such file or directory [ E:\tools\temp\cremi\cremi.vcxproj]

    Предупреждений: 26
    Ошибок: 1

**Comment by cyberpro4** [comment]
You need to download microhttpd library and include his headers files inside default include directories. [https://www.gnu.org/software/libmicrohttpd/](https://www.gnu.org/software/libmicrohttpd/)
Sorry for late response
